### ISSUE TITLE
LINC-OE: Traffic is not going through due to some updates in LINC

### ISSUE THREAD

**Issue by fnkhan** [FlowForwarding/LINC-Switch#353]
I recently pull the LINC new code and now traffic is not going through. But when i switch back to old commit it works fine.

Not Working for commit:
============
commit fe12e57abad85784b25ef1a16a293db33be1dc36
Merge: 0d6b7bc d51f609
Author: Szymon Mentel <szymon.mentel@erlang-solutions.com>
Date:   Thu Jan 29 15:19:50 2015 +0100

    Merge pull request #352 from FlowForwarding/travis-erl-17.3
    
    Make Travis use Erlang 17.3

Worrking for commit:
================

commit a412b0f26cc4e2ac84380f3be4140035edf26563
Author: Szymon Mentel <szymon.mentel@erlang-solutions.com>
Date:   Thu Jan 8 13:50:42 2015 +0100

    Fix typos in optical_extension.md

**Comment by mentels** [comment]
@fnkhan could you provide your sys.config file and the flow_mods that you send to the switch?

**Comment by fnkhan** [comment]
Hi Szymon,
		Thanks for noticing the issue. Basically I’m trying to connect  h1 (10.0.0.1) to h5 (10.0.0.5) in this particular case but new updates in LINC are not allowing it send traffic. ONOS-Intentes are getting installed correctly but traffic is not going through.

-Its doesn’t matter which sys.config I’m using, LINC is not working for anyone of them. In any case, to help you replicate the scenario I have attached my sys.config.


-Flows is the screenshot of flows and Topology_ONOS_GUI is the screenshot of ONOS-GUI.

Erlang Version:
===========
I have tried it with both Erlang-15 and Erlang-17.4.



> On which OS

My OS is Ubuntu-14.

> how do you use the OS interfaces?

I’m not sure what do you mean by that. Can you please explain?



-opticalTest.py is the mininet script that i use to create topology.



-Same setup works perfectly fine with a412b0f commit.

Tip on How to reproduce:
========================
We have a tutorial https://wiki.onosproject.org/display/ONOS/Packet+Optical+Tutorial
You can just download and follow the instructions.
You just need to pull the latest code for LINC.

Best Regards,
Fahad Naeem Khan.

**Comment by mentels** [comment]
@fnkhan I tried to run the [tutorial](https://wiki.onosproject.org/display/ONOS/Packet+Optical+Tutorial) but it seems not working for me - for example `pingall` fails and ONOS GUI is not accessible. Do you know why?

Regarding the problem with traffic I guess that it occurs because in cd943e817c6821ceb35eb4bd98fec761f81bdcf2 we added support for monitoring status of OS interfaces' state. For example LINC-Switch detects when an interface goes down/up and sends appropriate OpenFlow Port Status message to the controller. But for this to work the TUN/TAP interfaces that are to be used by LINC-Switch has to be **created** and **brought up** before the LINC-Switch starts. Otherwise they are in *UNKNOWN* state (run `ip addr show` after running opticalTest.py to see that) which is interpreted as *link down* and LINC-Switch treats such an interfaces as not accessible.

The solution for that would be to configure the TUN/TAPs as described above or make LINC treat the *UNKNOWN* state as *UP*.

**Comment by fnkhan** [comment]
Hi Szymon,
		pingall won’t work as you have to first send intents request to ONOS from the GUI or CLI. I don’t why GUI not working for you but you can add intent from the CLI using follow command

onos>add-point-intent <dpid/port> <dpid/port>

e.g from h1 to h2 you can do it like

add-point-intent of:0000ffffffff0001/1 of:0000ffffffff0002/1 

And yes you are write all tap are in unknown state 
88: tap32: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ovs-system state UNKNOWN group default qlen 500
    link/ether aa:c3:ea:bd:7a:2e brd ff:ff:ff:ff:ff:ff
89: tap31: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ovs-system state UNKNOWN group default qlen 500
    link/ether 3e:5c:d9:a9:38:43 brd ff:ff:ff:ff:ff:ff
90: tap30: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ovs-system state UNKNOWN group default qlen 500
    link/ether f6:dc:85:19:3d:7b brd ff:ff:ff:ff:ff:ff
91: tap34: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ovs-system state UNKNOWN group default qlen 500
    link/ether 3a:f3:c7:66:1b:e5 brd ff:ff:ff:ff:ff:ff
92: tap29: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ovs-system state UNKNOWN group default qlen 500
    link/ether 02:63:28:f8:a3:86 brd ff:ff:ff:ff:ff:ff
93: tap35: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ovs-system state UNKNOWN group default qlen 500
    link/ether e6:91:0b:84:dc:20 brd ff:ff:ff:ff:ff:ff
94: tap33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ovs-system state UNKNOWN group default qlen 500
    link/ether 6e:7b:10:cd:85:27 brd ff:ff:ff:ff:ff:ff
As tap are created when we start LINC so we can not create and bring them up before hand so second option seems more appropriate or some other alternative.

**Comment by mentels** [comment]
@fnkhan I managed to start the GUI but had to do that manually from the ONOS console: `features:install onos-gui`. Unfortunately I was not able to setup Host-To-Host flows: neither through the GUI by clicking on the appropriate button nor via the console. I verified that by trying to send pings from Mininet console. After inspecting the logs of LINC-OE there was no information  on flow mods. Thus I was not able to reproduce the issue. Are you responsible for the tutorial or should I post the aforementioned problems in the mailing list?

However, I managed to configure the interfaces so that they are in UP state after starting LINC-OE. Here is the slightly modified [opticalUtils.py](https://gist.github.com/mentels/1d9510ff2c2aa83a1df5). I create TUN/TAP interfaces and bring them up before starting LINC-OE (`setupInts(Intfs)` function). I also commented out `waitStarted( net )`. If you just extract appropriate interfaces names from the sys.config I see no problem with setting them up before starting LINC-OE.

With this modified `opticalUtils.py` the `ip addr show` output looks as follows:
`
462: tap29: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ovs-system state UP group default qlen 500
    link/ether ee:83:8e:79:f1:bc brd ff:ff:ff:ff:ff:ff
463: tap30: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ovs-system state UP group default qlen 500
    link/ether 02:01:99:f5:82:44 brd ff:ff:ff:ff:ff:ff
464: tap31: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ovs-system state UP group default qlen 500
    link/ether 92:84:b7:9f:2e:fb brd ff:ff:ff:ff:ff:ff
465: tap32: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ovs-system state UP group default qlen 500
    link/ether 9e:16:ce:a0:e2:fa brd ff:ff:ff:ff:ff:ff
466: tap33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ovs-system state UP group default qlen 500
    link/ether f2:4d:df:d3:b9:ca brd ff:ff:ff:ff:ff:ff
467: tap34: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ovs-system state UP group default qlen 500
    link/ether ba:5d:14:ec:d4:a5 brd ff:ff:ff:ff:ff:ff
468: tap35: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master ovs-system state UP group default qlen 500
    link/ether 72:cb:7d:dd:39:53 brd ff:ff:ff:ff:ff:ff
`

**Comment by fnkhan** [comment]
Hi Szymon,
		Nice patch, that worked fine. I have added a function to get all tap from the sys.config. I have attach the opticalUtils.py so that you can have a look.  
>  should I post the aforementioned problems in the mailing list?
> 
Yes please create a issue for that.

Issue is fixed, so should I close it or you will close it?

Thanks Szymon for you time and effort.
Fahad.

**Comment by mentels** [comment]
@fnkhan I don't know how to create an issue. The issue about "no traffic" is flowing is fixed but the optical tutorial doesn't work for me because setting Host-To-Host flow via GUI has no effect. And as I mentioned before ONOS GUI has to be enabled manually via ONOS console - the tutorial doesn't mention that.

And I am not able to see any attachment.

**Comment by fnkhan** [comment]
Hi Szymon,
		Yesterday I tried the tutorial VM and worked perfectly fine for me. Can you send me the output of of the ONOS logs. You can get by running the following command in ONOS CLI.

onos>log:display

and also the output of (installed features) 

onos>feature:list -i

 Fahad.

**Comment by fnkhan** [comment]
Hi Szymon,
		One more thing, CLI commands linc:start_switch() and stop_switch are not working.
(linc@mininet-vm)1> linc:stop_switch(2).
** exception exit: {noproc,{gen_server,call,
                                       [linc_capable_sup,{terminate_child,linc2_sup},infinity]}}
     in function  gen_server:call/3 (gen_server.erl, line 190)

**Comment by mentels** [comment]
Duplicated in #354
